### ISSUE TITLE
Add Python .xcframework for visionOS.

### ISSUE THREAD

**Issue by melchior-voidwolf** [wabiverse/MetaversePythonFramework#13]
Building for 'visionOS-simulator', but linking in object file (/Users/kail/Library/Developer/Xcode/DerivedData/moon-player-ekcqdkvzbilqlgdszhtevxyzgiwg/Build/Products/Debug-xrsimulator/libpython3.11.a[arm64][2](getbuildinfo.o)) built for 'macOS'

**Comment by furby-tm** [comment]
Hey @melchior-voidwolf!

Thank you for your interest in the **MetaverseKit** project, and I appreciate you taking the time to submit an issue ticket for this.

I have not yet gotten around to building the Python library for **visionOS**, once I add the binary **.xcframework** to [MetaversePythonFramework](https://github.com/wabiverse/MetaversePythonFramework) for that platform - I believe it should then be in working order.

Thanks for letting me know!

**Comment by furby-tm** [comment]
Fixed as of [**v3.11.7**](https://github.com/wabiverse/MetaversePythonFramework/releases/tag/v3.11.7).
